name: base

on: [push]

jobs:
  comandos:
    runs-on: ubuntu-latest
    steps:
      - name: comandos linux
        run: |
         whoami 
         pwd
         ls /
         date
         uname -a
         echo "este es un mensaje echo"
         ls -la /home
