name: Condiciones

on: [push, pull_request]

jobs:
  ejemplo:
    runs-on: ubuntu-latest
    steps:
      - name: descargar repo
        uses: actions/checkout@v4 
      - run: ls -la
     
      - name: 2. Crear artefacto con el proyecto
        uses: actions/upload-artifact@v4
        with:
          name: mi-proyecto-completo       
          path: .                          
          retention-days: 7    
